// <auto-generated />
namespace Vendord.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class addUserProfileTable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addUserProfileTable));
        
        string IMigrationMetadata.Id
        {
            get { return "201308260210503_addUserProfileTable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
