// <auto-generated />
namespace Vendord.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class productSchemeViaFluent : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(productSchemeViaFluent));
        
        string IMigrationMetadata.Id
        {
            get { return "201308250149031_productSchemeViaFluent"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
