// <auto-generated />
namespace Vendord.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class vendorProductViewFluent : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(vendorProductViewFluent));
        
        string IMigrationMetadata.Id
        {
            get { return "201308250237555_vendorProductViewFluent"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
