// <auto-generated />
namespace Prototype.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AddUpc : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddUpc));
        
        string IMigrationMetadata.Id
        {
            get { return "201307162236427_AddUpc"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
